services:
  # Servicio para el backend
  - type: web
    name: grupo-alabanza-backend
    env: node
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    region: ohio
    envVars:
      - key: DB_CONN_STRING
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONT_URL
        value: https://grupo-alabanza.onrender.com
      - key: PORT
        value: 10000

  # Servicio para el frontend
  - type: web
    name: grupo-alabanza
    env: node
    plan: free
    rootDir: frontend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm install -g serve && serve -s dist -l $PORT
    region: ohio
    envVars:
      - key: VITE_BACKEND_URL
        value: https://grupo-alabanza-backend.onrender.com
      - key: VITE_SKIP_TS_CHECK
        value: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 