services:
  # Servicio para el backend
  - type: web
    name: grupoalabanza-backend
    env: node
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        sync: false # Se configurará manualmente en el panel de Render
      - key: MONGODB_URI
        sync: false # Se configurará manualmente en el panel de Render
      - key: JWT_SECRET
        sync: false # Se configurará manualmente en el panel de Render
      - key: JWT_EXPIRATION
        value: 7d
    autoDeploy: true

  # Servicio para el frontend
  - type: web
    name: grupoalabanza-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: grupoalabanza-backend
          type: web
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true 